spring:
  application:
    name: enotes-api-service
  profiles:
    active: dev
    
---
# dev config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: techlife246@gmail.com
    password: yyjg zdkl aosq oksi
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
springdoc:
  swagger-ui:
    enabled: true
    path: /enotes-doc
    tryItOutEnabled: false
    operationsSorter: method
    tagsSorter: alpha
    authorizations: Authorization
    filter: false
  api-docs:
    enabled: true
    path: /enotes-api-doc
  packages-to-scan: com.becoder.controller  
    
  

file:
  upload:
    path: notes/
# api-docs.enabled=false if you want to disable springdoc-openapi endpoints
# swagger-ui.enabled=false to disable the swagger-ui endpoint.
---
# test config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: techlife246@gmail.com
    password: nflw mgjz qlld huay
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true       
file:
  upload:
    path: notes/
---
# uat config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: techlife246@gmail.com
    password: nflw mgjz qlld huay
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true       
file:
  upload:
    path: notes/
---
# prod config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: techlife246@gmail.com
    password: nflw mgjz qlld huay
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true       
file:
  upload:
    path: notes/
    
